version: "3.3"
services:  
  vsal:
    restart: on-failure
    build: ./VSAL-lab-website
    ports:
      - "3000:3000"
    networks:
      my-network:
        ipv4_address: 172.20.0.2

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - vsal



networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
